all:
  sfRabbitPlugin:
    connections:
      default:
        host:      localhost
        post:      5672
        user:      guest
        password:  guest
        vhost:     /

    producers:
      test:
        connection:       default
        exchange_options: {name: test, type: direct}

    consumers:
      test:
        connection:       default
        exchange_options: {name: test, type: direct}
        queue_options: {name: test}
        callback:         testCallback

